### PR TITLE
Use phenio (c/o ODK assembly)

### PR DESCRIPTION
**Pull request by caufieldjh**
* Download phenio-base.owl.tar.gz
* Preprocess with ROBOT (relax)
* Run SPARQL query (i.e., `update` or `construct` to include in the input rather than just get the result) to obtain expected relations
* Translate

### CODE REVIEW

**Comment by cmungall** [comment]
This works for subq patterns provided ontology is relaxed, cc @matentzn 

a sub p1 some (p2 some b):

```
SELECT ?a ?bN1 ?bN2 ?p1 ?p2 ?b WHERE {
  ?a <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?bN1 .
  ?bN2 <http://www.w3.org/2002/07/owl#onProperty> ?p1 .
  ?bN2 <http://www.w3.org/2002/07/owl#someValuesFrom> ?bN2 .
  ?bN2 <http://www.w3.org/2002/07/owl#onProperty> ?p2 .
  ?bN2 <http://www.w3.org/2002/07/owl#someValuesFrom> ?b}
```

**Comment by caufieldjh** [comment]
Note that updating PHENIO as above is applicable both to all successive downstream use of PHENIO and of other instances where we want to produce relations from subq patterns

**Comment by caufieldjh** [comment]
Just need to replace `SPARQLWrapper` with something like rdflib since we have the file locally

**Comment by matentzn** [comment]
I am not going to comment on this... Go ahead 😱 

HP and MP are not relaxed so this wont work here. I think it may be better to put pressure on https://github.com/mgijax/mammalian-phenotype-ontology/pull/3480

**Comment by justaddcoffee** [comment]
@matentzn I think the plan was to do a robot relax beforehand, would this not solve that problem?

I'd be glad to help lobby for a better solution in the long term, if I can help - if I understand correctly though, this would take a fairly long time to make its way back into phenio, right? We'll need to do the kg-phenio experiment sooner than taht

**Comment by matentzn** [comment]
Ah so you want to preprocess MP/HP before running it through this process? you don't really need to extend KGX at all then, just run robot to relax and  sparql to preprocess the ontology, and then cycle it through KGX is normal - no need for any "special handling" of subq in KGX if you have to relax anyways..

**Comment by justaddcoffee** [comment]
> Ah so you want to preprocess MP/HP before running it through this process? you don't really need to extend KGX at all then, just run robot to relax and sparql to preprocess the ontology, and then cycle it through KGX is normal - no need for any "special handling" of subq in KGX if you have to relax anyways..

Yep, the plan is to just use robot relax and a sparql query so we don't have to hack into KGX to fix this

**Comment by caufieldjh** [comment]
As per conversation with @cmungall this will likely be much more efficient with `robot query` in lieu of `rdflib`.
Can also try with [relation-graph](https://github.com/balhoff/relation-graph) for prototyping or can export to TDB to do the querying (http://robot.obolibrary.org/query#executing-on-disk)

**Comment by caufieldjh** [comment]
Note that robot wants query prefixes to be defined or it throws this error:
```
  STDERR:
java.io.IOException: query#QUERY PARSE ERROR query cannot be parsed:
Line 1, column 16: Unresolved prefixed name: rdfs:subClassOf
        at org.obolibrary.robot.QueryOperation.runSparqlQuery(QueryOperation.java:657)
        at org.obolibrary.robot.QueryCommand.runQueries(QueryCommand.java:411)
        at org.obolibrary.robot.QueryCommand.executeInMemory(QueryCommand.java:235)
        at org.obolibrary.robot.QueryCommand.execute(QueryCommand.java:188)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
```

**Comment by caufieldjh** [comment]
ROBOT has a temp file option for query (see https://github.com/ontodev/robot/pull/980) but it isn't in a release yet

**Comment by caufieldjh** [comment]
This is now working as expected, with the caveat that far fewer subq patterns are parsed as would be preferable. I'll open a separate issue + PR for that so this can be merged and used for the OntoML projects.

**Pull request merged**
